---
- name: 1.2.2.1 | Ensure updates, patches, and additional security software are installed | Manual Actions Report
  when: cis_ubuntu2404_package_updates_check_report
  dtvlinux.cis_hardening.check_package_updates:
    current_manual_actions: "{{ ansible_facts['cis_manual_actions'] | default([]) }}"
  changed_when: false
  tags:
    - cis_ubuntu2404_rule_1_2_2_1
    - cis_ubuntu2404_level_1_server
    - cis_ubuntu2404_level_1_workstation
    - cis_ubuntu2404_control_7_3
    - cis_ubuntu2404_control_7_4
    - cis_ubuntu2404_ig_1
    - cis_ubuntu2404_ig_2
    - cis_ubuntu2404_ig_3
