---
galaxy_info:
  author: dtvlinux
  description: System hardening tasks for security
  license: MIT
  min_ansible_version: "2.19.0"
  platforms:
    - name: EL
      versions:
        - "10"
    - name: Ubuntu
      versions:
        - noble # 24.04
dependencies: []
