---
- name: 1.2.1.1 | Ensure GPG keys are configured | Manual Actions Report
  when: cis_ubuntu2404_gpg_key_check_report
  dtvlinux.cis_hardening.check_gpg_keys:
    current_manual_actions: "{{ ansible_facts['cis_manual_actions'] | default([]) }}"
  changed_when: false
  tags:
    - cis_ubuntu2404_rule_1_2_1_1
    - cis_ubuntu2404_level_1_server
    - cis_ubuntu2404_level_1_workstation
    - cis_ubuntu2404_control_7_3
    - cis_ubuntu2404_control_7_4
    - cis_ubuntu2404_ig_1
    - cis_ubuntu2404_ig_2
    - cis_ubuntu2404_ig_3

- name: 1.2.1.2 | Ensure package manager repositories are configured | Manual Actions Report
  when: cis_ubuntu2404_repositories_check_report
  dtvlinux.cis_hardening.check_repositories:
    current_manual_actions: "{{ ansible_facts['cis_manual_actions'] | default([]) }}"
  changed_when: false
  tags:
    - cis_ubuntu2404_rule_1_2_1_2
    - cis_ubuntu2404_level_1_server
    - cis_ubuntu2404_level_1_workstation
    - cis_ubuntu2404_control_7_3
    - cis_ubuntu2404_control_7_4
    - cis_ubuntu2404_ig_1
    - cis_ubuntu2404_ig_2
    - cis_ubuntu2404_ig_3
