---
- name: 1.1.1 | Configure filesystem kernel modules | Import tasks
  when: cis_1_1_1_apply
  ansible.builtin.import_tasks:
    file: 1_1_1_configure_filesystem_kernel_modules.yml
  tags: "cis_1_1_1"

- name: 1.1.2 | Configure filesystem partitions | Import tasks
  when: cis_1_1_2_apply
  ansible.builtin.import_tasks:
    file: 1_1_2_configure_filesystem_partitions.yml
  tags: "cis_1_1_2"
