---
- name: 1.2.1 | Configure Package Repositories | Import tasks
  ansible.builtin.import_tasks:
    file: 1_2_1_package_repos/main.yml

- name: 1.2.2 | Configure Package Updates | Import tasks
  ansible.builtin.import_tasks:
    file: 1_2_2_package_updates/main.yml
