---
- name: 1.1.1 | Configure filesystem kernel modules | Import tasks
  ansible.builtin.import_tasks:
    file: 1_1_1_kernel_modules/main.yml

- name: 1.1.1 | Configure filesystem kernel modules | Import tasks
  ansible.builtin.import_tasks:
    file: 1_1_2_partitions/main.yml
